const FabData: any = {
  MFAB2: [
    {
      IMG: 'public/img/models/MP2_RS6000.png',
      EQUIPMENT: 'MFAB2_RS6000',
      LINK: '',
      TOP: '21',
      RIGHT: '53',
    },
    {
      IMG: 'public/img/models/MP2_INTEGER_PLUS.png',
      EQUIPMENT: 'MFAB2_INTEGER_PLUS',
      LINK: '',
      TOP: '15',
      RIGHT: '45',
    },
    {
      IMG: 'public/img/models/MP2_SUPRA_XP.png',
      EQUIPMENT: 'MFAB2_SUPRA_XP',
      LINK: '',
      TOP: '14',
      RIGHT: '37',
    },
    {
      IMG: 'public/img/models/MP2_SUPRA_N.png',
      EQUIPMENT: 'MP2_SUPRA_N',
      LINK: '',
      TOP: '10',
      RIGHT: '28',
    },
    {
      IMG: 'public/img/models/MP2_SUPRA_N.png',
      EQUIPMENT: 'MP2_SUPRA_N',
      LINK: '',
      TOP: '6',
      RIGHT: '20',
    },
  ],
  RLAB: [
    {
      IMG: 'public/img/models/R_LAB_PRECIA.png',
      EQUIPMENT: 'R_LAB_PRECIA',
      LINK: 'd/OFr97CuMk/eq-information',
      TOP: '35',
      LEFT: '5',
      NAME: 'PVK28704',
    },
    {
      IMG: 'public/img/models/R_LAB_OMNIS.png',
      EQUIPMENT: 'R_LAB_OMNIS',
      LINK: 'd/FsgvgCXMe/eq-information',
      TOP: '52',
      LEFT: '33',
      NAME: 'PAK29714',
    },
    {
      IMG: 'public/img/models/R_LAB_PRECIA_2.png',
      EQUIPMENT: 'R_LAB_PRECIA_2',
      LINK: 'd/OFr97CuMa/eq-information',
      TOP: '46',
      LEFT: '47',
      NAME: 'PVK30709',
    },
    {
      IMG: 'public/img/models/R_LAB_SUPRA_N.png',
      EQUIPMENT: 'R_LAB_SUPRA_N',
      LINK: '',
      TOP: '39',
      LEFT: '61',
      NAME: 'PJK29707',
    },
    {
      IMG: 'public/img/models/R_LAB_SUPRA_XP.png',
      EQUIPMENT: 'R_LAB_SUPRA_XP',
      LINK: '',
      TOP: '8',
      LEFT: '62',
      NAME: 'PZK26701',
    },
    {
      IMG: 'public/img/models/R_LAB_RE3500.png',
      EQUIPMENT: 'R_LAB_RE3500',
      LINK: 'd/Ug5XBPXMk/2-measurement-history',
      TOP: '7',
      LEFT: '78',
      NAME: 'RE3500(R)',
    },
  ],
  PLAB: [
    {
      IMG: 'public/img/models/INTEGER_PLUS.png',
      EQUIPMENT: 'INTEGER_PLUS',
      LINK: 'd/r-BliCuGk/eq-information',
      TOP: '35',
      LEFT: '5',
      NAME: 'PNK15009',
    },
    {
      IMG: 'public/img/models/TIGMA_NM.png',
      EQUIPMENT: 'TIGMA_NM',
      LINK: '',
      TOP: '29',
      LEFT: '19',
      NAME: 'PGK15038',
    },
    {
      IMG: 'public/img/models/SUPRA_XP.png',
      EQUIPMENT: 'SUPRA_XP',
      LINK: '',
      TOP: '21',
      LEFT: '33',
      NAME: 'PQK30716',
    },
    {
      IMG: 'public/img/models/SUPRA_N.png',
      EQUIPMENT: 'SUPRA_N',
      LINK: '',
      TOP: '15',
      LEFT: '47',
      NAME: 'PGK15025',
    },
    {
      IMG: 'public/img/models/INTEGER_XP.png',
      EQUIPMENT: 'INTEGER_XP',
      LINK: 'd/CtPKrRJik/eq-information',
      TOP: '5',
      LEFT: '61',
      NAME: 'PNK27718',
    },
    {
      IMG: 'public/img/models/SUPRA_N2.png',
      EQUIPMENT: 'SUPRA_N2',
      LINK: '',
      TOP: '61',
      LEFT: '20',
      NAME: 'PGK27880',
    },
    {
      IMG: 'public/img/models/INTEGER_PLUS2.png',
      EQUIPMENT: 'INTEGER_PLUS2',
      LINK: 'd/r-BliCuGd/eq-information',
      TOP: '53',
      LEFT: '35',
      NAME: 'PNK28712',
    },
    {
      IMG: 'public/img/models/SUPRA_XP2.png',
      EQUIPMENT: 'SUPRA_XP2',
      LINK: '',
      TOP: '46',
      LEFT: '49',
      NAME: 'PQK28708',
    },
    {
      IMG: 'public/img/models/OMNIS.png',
      EQUIPMENT: 'OMNIS',
      LINK: 'd/FsgvgCXMk/eq-information',
      TOP: '39',
      LEFT: '63',
      NAME: 'PAK09002',
    },
    {
      IMG: 'public/img/models/RE3500.png',
      EQUIPMENT: 'RE3500',
      LINK: 'd/VrQejhuMz/2-measurement-history',
      TOP: '32',
      LEFT: '77',
      NAME: 'RE3500(P)',
    },
    {
      IMG: 'public/img/models/LS9300.png',
      EQUIPMENT: 'LS9300',
      LINK: 'd/0Yv31EuGz/particle-history',
      TOP: '6',
      LEFT: '77',
      NAME: 'LS9300',
    },
  ],
  MFAB1: [
    {
      IMG: 'public/img/models/RE3100.png',
      EQUIPMENT: 'RE3100',
      LINK: '',
      TOP: '7',
      LEFT: '80',
      NAME: 'RE3100',
    },
  ],
};
export default FabData;
